### PR TITLE
RAI-24760 Handle token directory creation

### PR DESCRIPTION
**Pull request by ginal**
Create the token cache directory if the directory does not exist.

### CODE REVIEW

**Comment by larf311** [comment]
Please add tests.

**Comment by ginal** [comment]
Added tests.

**Comment by Akrion** [comment]
I tested the main and this branch running the unit tests. In main I get no errors but in this branch I do get:

```error deleting token cache file directory: /Users/ialexiev/.rai: remove /Users/ialexiev/.rai: directory not empty```

CleanShot 2024-07-11 at 15 11 23@2x

All tests pass both cases though

**Comment by ginal** [comment]
> I tested the main and this branch running the unit tests. In main I get no errors but in this branch I do get:
> 
> `error deleting token cache file directory: /Users/ialexiev/.rai: remove /Users/ialexiev/.rai: directory not empty`

I have updated the commit and removed the error logging.

**Review by Akrion — APPROVED** [review]

**Pull request merged**
