### PR TITLE
Prevent tests panics

### PR DESCRIPTION
**Pull request by NRHelmi**
This PR prevents tests panics that lead to not cleaned up resources
closes https://github.com/RelationalAI/rai-sdk-go/issues/50

### CODE REVIEW

**Comment by miazamrai** [comment]
@NRHelmi Just for curiosity, is there a way to define a after all tests kind of method which we can do in Java or C#?

**Comment by NRHelmi** [comment]
> @NRHelmi Just for curiosity, is there a way to define a after all tests kind of method which we can do in Java or C#?

AFAIK no easy way to do so, one option probably is to use `defer` in golang

**Comment by miazamrai** [comment]
> > @NRHelmi Just for curiosity, is there a way to define a after all tests kind of method which we can do in Java or C#?
> 
> AFAIK no easy way to do so, one option probably is to use `defer` in golang

What about this?
 https://stackoverflow.com/questions/23729790/how-can-i-do-test-setup-using-the-testing-package-in-go
 We are already doing something here
 https://github.com/RelationalAI/rai-sdk-go/blob/main/rai/main_test.go

**Comment by NRHelmi** [comment]
> > > @NRHelmi Just for curiosity, is there a way to define a after all tests kind of method which we can do in Java or C#?
> > 
> > 
> > AFAIK no easy way to do so, one option probably is to use `defer` in golang
> 
> What about this? https://stackoverflow.com/questions/23729790/how-can-i-do-test-setup-using-the-testing-package-in-go We are already doing something here https://github.com/RelationalAI/rai-sdk-go/blob/main/rai/main_test.go

I believe that's exactly what we are doing
```
func TestMain(m *testing.M) {
    setup()
    code := m.Run() 
    shutdown()
    os.Exit(code)
}
```

**Comment by torkins** [comment]
Seems like there's no way in the case of panics to cleanup resources in-process.. also here's an SO that briefly discusses it: https://stackoverflow.com/questions/51727970/go-tests-clean-up-after-panic

I don't love the fact that all of these checks make the tests so brittle (and easy to write a new test which causes a panic) so I think we need a refactoring, but we can make a ticket for that with a comprehensive approach. Fixing the panics is step 1.. we might want to look into wrapping a script to do cleanup although plenty of abstraction-piercing problems with that

**Review by torkins — APPROVED** [review]

**Comment by miazamrai** [comment]
> > > > @NRHelmi Just for curiosity, is there a way to define a after all tests kind of method which we can do in Java or C#?
> > > 
> > > 
> > > AFAIK no easy way to do so, one option probably is to use `defer` in golang
> > 
> > 
> > What about this? https://stackoverflow.com/questions/23729790/how-can-i-do-test-setup-using-the-testing-package-in-go We are already doing something here https://github.com/RelationalAI/rai-sdk-go/blob/main/rai/main_test.go
> 
> I believe that's exactly what we are doing
> 
> ```
> func TestMain(m *testing.M) {
>     setup()
>     code := m.Run() 
>     shutdown()
>     os.Exit(code)
> }
> ```

Yeah, but it is never called in case of panics. Like, the post shared by @torkins. Anyways, good for now.

**Pull request merged**
